# Generated by Django 4.0.1 on 2022-03-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='descriptionAuthor',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='author',
            name='nameAuthor',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
